In [3]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

# File to Load
data_to_load = "Resources/vine_table.csv"

# Read the data files and store them in a pandas DataFrame.
vine_data_df = pd.read_csv(data_to_load)
vine_data_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,RMDCHWD0Y5OZ9,3.0,0.0,1.0,N,N
1,RZSL0BALIYUNU,5.0,0.0,0.0,N,Y
2,RIZR67JKUDBI0,3.0,0.0,1.0,N,Y
3,R27HL570VNL85F,5.0,0.0,0.0,N,Y
4,R34EBU9QDWJ1GD,5.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
904760,R6MDTUK723YPY,4.0,143.0,148.0,N,N
904761,R10B4417NCK98O,5.0,24.0,24.0,N,N
904762,R3V2A0GUZ3JAQ4,4.0,27.0,29.0,N,N
904763,R1VYXC7FFG4LGH,4.0,46.0,49.0,N,N
904764,R2XJJXFZOM36V5,5.0,17.0,19.0,N,N

In [4]:
vine_data_df.dtypes

review_id             object
star_rating          float64
helpful_votes        float64
total_votes          float64
vine                  object
verified_purchase     object
dtype: object

In [5]:
# total_votes count is equal to or greater than 20
twenty_total_votes_df = vine_data_df[(vine_data_df["total_votes"] >= 20)]
twenty_total_votes_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
28,R2243Y3OD8U6KQ,5.0,47.0,61.0,N,N
85,R2TGT0CDTCAAHW,5.0,21.0,23.0,N,Y
457,RX4D22YSXEF4P,1.0,37.0,38.0,N,Y
1028,R3FL2NTLFUSPTQ,5.0,33.0,37.0,N,N
1039,R3QTP3YNZXAPPF,3.0,23.0,24.0,N,Y
...,...,...,...,...,...,...
904759,R2EJ952S3YK254,4.0,46.0,47.0,N,N
904760,R6MDTUK723YPY,4.0,143.0,148.0,N,N
904761,R10B4417NCK98O,5.0,24.0,24.0,N,N
904762,R3V2A0GUZ3JAQ4,4.0,27.0,29.0,N,N
904763,R1VYXC7FFG4LGH,4.0,46.0,49.0,N,N

In [24]:
# number of helpful_votes divided by total_votes is equal to or greater than 50%.
twenty_total_votes_df["vote_%"] = (twenty_total_votes_df["helpful_votes"] / twenty_total_votes_df["total_votes"]) * 100
# twenty_total_votes_df

fifty_percent_helpful_df = twenty_total_votes_df[(twenty_total_votes_df["vote_%"] >= 50)]
fifty_percent_helpful_df

C:\Users\Tony\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_%
904096,R2TXFUQOYNB24P,1.0,11.0,22.0,N,N,50.0
287686,R3HX2SO0MCZ8JY,3.0,11.0,22.0,N,Y,50.0
894854,R1J3A9I51LN3B9,2.0,10.0,20.0,N,N,50.0
795865,R4JLYKS3C0DQA,2.0,10.0,20.0,N,Y,50.0
889692,R3D5EAC4QGPSA8,1.0,13.0,26.0,N,Y,50.0
...,...,...,...,...,...,...,...
851437,R2MKCS0OP2XL83,5.0,30.0,30.0,N,Y,100.0
835671,R3GPSMK7XXHT7K,5.0,20.0,20.0,N,Y,100.0
903352,R2MQ4ZSA59HTDR,4.0,29.0,29.0,N,N,100.0
481905,R58RHVYWSRSC3,3.0,26.0,26.0,N,Y,100.0
679905,R2WPHN4MEB6YGN,4.0,29.0,29.0,N,Y,100.0

In [26]:
# retrieve all rows where a review was written as part of the Vine program (paid), vine == 'Y'.
vine_paid_df = fifty_percent_helpful_df[(fifty_percent_helpful_df["vine"] == "Y")]
vine_paid_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_%
497969,R1I98OVWL8N0X,3.0,16.0,28.0,Y,N,57.142857
658817,ROIU1G8UOP20L,3.0,14.0,22.0,Y,N,63.636364
816859,R2HT2LBF48R9HC,5.0,26.0,38.0,Y,N,68.421053
237635,R2016NFLSUR97Y,2.0,26.0,37.0,Y,N,70.270270
761174,RMCGLOIUS31A0,5.0,22.0,30.0,Y,N,73.333333
357373,R2A3FFNJTDUBMV,5.0,20.0,27.0,Y,N,74.074074
816778,R2YI9KHLBCF0NF,5.0,34.0,45.0,Y,N,75.555556
316563,R13PPTBWWV10Q6,5.0,19.0,25.0,Y,N,76.000000
73488,RKYLHZL7EPELX,4.0,19.0,25.0,Y,N,76.000000
508562,R113X83B4OZYF8,3.0,37.0,47.0,Y,N,78.723404
641917,R3VHUT5HS9V22R,4.0,19.0,24.0,Y,N,79.166667
513953,RARYFB85E8YSK,5.0,25.0,31.0,Y,N,80.645161
9120,R19EFYNN3W8Q07,5.0,26.0,32.0,Y,N,81.250000
425838,R2XBIPOLCU015D,4.0,23.0,28.0,Y,N,82.142857
759938,R3HCAEISSZTOPF,5.0,47.0,57.0,Y,N,82.456140
492630,R4KIRC319GP61,5.0,19.0,23.0,Y,N,82.608696
34704,R34DJ1R8AEU0SG,5.0,29.0,35.0,Y,N,82.857143
637573,R2Q5W1NNKF8ESR,5.0,20.0,24.0,Y,N,83.333333
440256,RX4P0ENQPW8JW,3.0,20.0,24.0,Y,N,83.333333
227822,R2SW4NXNO7HZJ5,4.0,28.0,33.0,Y,N,84.848485
190962,RYW05F1MUEF01,5.0,87.0,102.0,Y,N,85.294118
742766,RAGY9ISHYAS08,4.0,19.0,22.0,Y,N,86.363636
495259,R1UZW5KV87WUA1,5.0,26.0,30.0,Y,N,86.666667
366816,R3QQG4HUB214TM,5.0,111.0,128.0,Y,N,86.718750
4229,R1R9RU7JW0MFR2,4.0,20.0,23.0,Y,N,86.956522
640709,R1YGI7SDJBIITA,3.0,67.0,77.0,Y,N,87.012987
394836,R22CYBPLKWDK6F,5.0,47.0,54.0,Y,N,87.037037
400167,R1ETBDZ1LJ8CEL,4.0,28.0,32.0,Y,N,87.500000
366973,R3J9OSJNJB7KGM,5.0,70.0,80.0,Y,N,87.500000
423840,R1OIXASHDMAU84,5.0,35.0,40.0,Y,N,87.500000
443846,R33G6UUWX1SZ1W,4.0,36.0,41.0,Y,N,87.804878
522139,R2VRYZV3N49TJ0,4.0,29.0,33.0,Y,N,87.878788
559377,R2CCHT4ZV5ZM5X,4.0,22.0,25.0,Y,N,88.000000
177563,R1U13EKGQD3ZE6,5.0,22.0,25.0,Y,N,88.000000
596862,R35BSD0RCM94I2,3.0,128.0,145.0,Y,N,88.275862
652098,R1WYQYB9KX1WM1,5.0,32.0,36.0,Y,N,88.888889
447381,R3NGT6QJHCUOKV,4.0,34.0,38.0,Y,N,89.473684
594070,R1HZ9P5BJJZWNU,3.0,61.0,68.0,Y,N,89.705882
766961,R2XWB7UZBANOS3,4.0,18.0,20.0,Y,N,90.000000
38510,R25P5CXK5L9RHF,5.0,146.0,161.0,Y,N,90.683230
307453,RFCV9QXJ3D79X,3.0,20.0,22.0,Y,N,90.909091
680512,R2ID3IBRNPEAKZ,5.0,42.0,46.0,Y,N,91.304348
436145,R6BXKPVUVXBTT,4.0,43.0,47.0,Y,N,91.489362
312863,R36779ZAY4ZT0Y,3.0,46.0,50.0,Y,N,92.000000
559334,RP24DFOZY82Z9,5.0,24.0,26.0,Y,N,92.307692
510047,R3QE0Q8R65G2M9,5.0,52.0,56.0,Y,N,92.857143
509123,R394FJYWZ0GNFG,5.0,40.0,43.0,Y,N,93.023256
428102,R30FS6HFPQ1WKT,5.0,41.0,44.0,Y,N,93.181818
49330,R2E9VZB3I4LSN5,5.0,55.0,59.0,Y,N,93.220339
577368,R2UP2773CHKTE3,5.0,71.0,76.0,Y,N,93.421053
544991,R6PO4CRQ8RWVP,4.0,34.0,36.0,Y,N,94.444444
519257,R295FZN1I3KSQM,5.0,71.0,75.0,Y,N,94.666667
403075,R28T5ISQ8AA7E5,5.0,40.0,42.0,Y,N,95.238095
367038,RIMYDUAAFXY2U,5.0,22.0,23.0,Y,N,95.652174
635654,R2ZVYKSW84Z47N,5.0,67.0,70.0,Y,N,95.714286
537659,R27L14PCLC87MI,5.0,70.0,73.0,Y,N,95.890411
644593,R25AJSJ49JA89T,5.0,61.0,63.0,Y,N,96.825397
736368,R1LLUVTO5GEFHS,4.0,40.0,41.0,Y,N,97.560976
641839,R2UJHZ50AMCITI,5.0,22.0,22.0,Y,N,100.000000
820981,R3Q3WCJO38879H,4.0,25.0,25.0,Y,N,100.000000

In [27]:
# retrieve all rows where a review was written NOT part of the Vine program (paid), vine == 'N'.
vine_unpaid_df = fifty_percent_helpful_df[(fifty_percent_helpful_df["vine"] == "N")]
vine_unpaid_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_%
904096,R2TXFUQOYNB24P,1.0,11.0,22.0,N,N,50.0
287686,R3HX2SO0MCZ8JY,3.0,11.0,22.0,N,Y,50.0
894854,R1J3A9I51LN3B9,2.0,10.0,20.0,N,N,50.0
795865,R4JLYKS3C0DQA,2.0,10.0,20.0,N,Y,50.0
889692,R3D5EAC4QGPSA8,1.0,13.0,26.0,N,Y,50.0
...,...,...,...,...,...,...,...
851437,R2MKCS0OP2XL83,5.0,30.0,30.0,N,Y,100.0
835671,R3GPSMK7XXHT7K,5.0,20.0,20.0,N,Y,100.0
903352,R2MQ4ZSA59HTDR,4.0,29.0,29.0,N,N,100.0
481905,R58RHVYWSRSC3,3.0,26.0,26.0,N,Y,100.0
679905,R2WPHN4MEB6YGN,4.0,29.0,29.0,N,Y,100.0

In [31]:
vine_paid_df.count()

review_id            60
star_rating          60
helpful_votes        60
total_votes          60
vine                 60
verified_purchase    60
vote_%               60
dtype: int64

In [34]:
# retrieve rows where vine is paid ("Y") and a five star review is given
vine_paid_5star_df = vine_paid_df[(vine_paid_df["star_rating"] >= 5)]
vine_paid_5star_df.count()

review_id            34
star_rating          34
helpful_votes        34
total_votes          34
vine                 34
verified_purchase    34
vote_%               34
dtype: int64

In [35]:
vine_unpaid_df.count()

review_id            14477
star_rating          14477
helpful_votes        14477
total_votes          14477
vine                 14477
verified_purchase    14477
vote_%               14477
dtype: int64

In [36]:
# retrieve rows where vine is NOT paid ("N") and a five star review is given
vine_unpaid_5star_df = vine_unpaid_df[(vine_unpaid_df["star_rating"] >= 5)]
vine_unpaid_5star_df.count()

review_id            8212
star_rating          8212
helpful_votes        8212
total_votes          8212
vine                 8212
verified_purchase    8212
vote_%               8212
dtype: int64

In [38]:
# retrieve rows where vine is paid ("Y") and a four star review is given
vine_paid_4star_df = vine_paid_df[(vine_paid_df["star_rating"] >= 4)]
vine_paid_4star_df.count()

review_id            50
star_rating          50
helpful_votes        50
total_votes          50
vine                 50
verified_purchase    50
vote_%               50
dtype: int64

In [39]:
# retrieve rows where vine is paid ("Y") and a four star review is given
vine_unpaid_4star_df = vine_unpaid_df[(vine_unpaid_df["star_rating"] >= 4)]
vine_unpaid_4star_df.count()

review_id            10899
star_rating          10899
helpful_votes        10899
total_votes          10899
vine                 10899
verified_purchase    10899
vote_%               10899
dtype: int64